<?php


namespace App\Controller;


use App\Model\Entity\User;

class UsersController extends AppController
{
public function initialize(): void
{
    parent::initialize(); // TODO: Change the autogenerated stub
    $this->Authentication->allowUnauthenticated(['login','signin']);
}

public function login()
{
$user = $this->Users->newEmptyEntity();
if(!empty($this->getRequest()->getData())){

    $result = $this->Authentication->getResult();

    if($result->isValid()){
        $target = $this->Authentication->getLoginRedirect() ?? '/';
        return $this->redirect($target);
    }
    if($this->getRequest()->is('Post') && !$result->isValid()){
        $this->Flash->error('Mot de passe non valide');
    }
    // If the user is logged in send them away.

}
$this->set(compact('user'));

}

public function  signin(){
    $user= ['email'=>'test@gmail.com', 'password'=>'1234'];
    $userEntity = $this->Users->newEntity($user);
    $this->Users->save($userEntity);
    die('ok');
}

}
